# Generated by Django 6.0 on 2026-01-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/'),
        ),
    ]
